### ISSUE TITLE
[EPIC] Create Quick Pick Award

### ISSUE THREAD

**Issue by johnsturgeon** [TheGreatFootballPool/tgfp-web#146]
- [ ] Write a helper script to give me the first player who did their picks for the week
- [ ] Add `created_at` timestamp to the `pick` model
- [ ] Add code to automatically timestamp the `created_at` timestamp
